import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseBudget, upsertTotals, budgetTemplate, renderTotals } from '../src/core/budget';

const BUDGET = `# Budget — Test

## Production

| Item | Estimate | Actual | Notes |
|------|----------|--------|-------|
| Crew | $1,000 | 1200.50 | ot |
| Camera | 500 | | rental |

## Post

| Item | Estimate | Actual | Notes |
|------|----------|--------|-------|
| Edit | 300 | 250 | |
`;

test('parseBudget sums sections and grand totals', () => {
  const b = parseBudget(BUDGET);
  assert.equal(b.sections.length, 2);
  assert.equal(b.sections[0].estimate, 1500);
  assert.equal(b.sections[0].actual, 1200.5);
  assert.equal(b.estimate, 1800);
  assert.equal(b.actual, 1450.5);
  assert.equal(b.sections[0].lines[1].actual, null);
});

test('upsertTotals appends then replaces in place', () => {
  const once = upsertTotals(BUDGET);
  assert.match(once, /## Totals/);
  assert.match(once, /\| Production \| \$1,500 \| \$1,200\.5 \|/);
  assert.match(once, /\*\*Total\*\* \| \*\*\$1,800\*\*/);
  // Running again must not duplicate the section or re-ingest it into totals.
  const twice = upsertTotals(once);
  assert.equal((twice.match(/## Totals/g) ?? []).length, 1);
  assert.match(twice, /\*\*Total\*\* \| \*\*\$1,800\*\*/);
});

test('totals section stays put when other sections follow it', () => {
  const withTail = upsertTotals(BUDGET) + '\n## Notes\n\nfree text\n';
  const updated = upsertTotals(withTail);
  assert.match(updated, /## Notes/);
  assert.equal((updated.match(/## Totals/g) ?? []).length, 1);
});

test('template parses cleanly with zero totals', () => {
  const b = parseBudget(budgetTemplate('X'));
  assert.equal(b.sections.length, 4);
  assert.equal(b.estimate, 0);
});

test('variance directions', () => {
  const over = upsertTotals('## S\n\n| Item | Estimate | Actual |\n|--|--|--|\n| a | 100 | 150 |\n');
  assert.match(over, /\+\$50 over/);
  const under = upsertTotals('## S\n\n| Item | Estimate | Actual |\n|--|--|--|\n| a | 100 | 80 |\n');
  assert.match(under, /\$20 under/);
});

test('user notes below the Totals table survive regeneration', () => {
  const withNotes = upsertTotals(BUDGET) + '\nrenegotiate crew rate\ninsurance quote pending\n';
  const updated = upsertTotals(withNotes);
  assert.match(updated, /renegotiate crew rate/);
  assert.match(updated, /insurance quote pending/);
  assert.equal((updated.match(/## Totals/g) ?? []).length, 1);
});

test('h3 subsection between Totals and next h2 survives', () => {
  const doc = upsertTotals(BUDGET).replace(/$/, '\n### Notes from producer\n\nKeep this paragraph.\n\n## Appendix\n\nmisc\n');
  const updated = upsertTotals(doc);
  assert.match(updated, /### Notes from producer/);
  assert.match(updated, /Keep this paragraph\./);
  assert.match(updated, /## Appendix/);
});

test('legacy Totals block without end sentinel is bounded by the table, not the next h2', () => {
  const legacy = `${BUDGET}\n## Totals\n\n<!-- generated by ScreenMark — edits here are overwritten -->\n\n| Section | Estimate | Actual | Variance |\n|--|--|--|--|\n| Production | $1 | $1 | — |\n\nkeep me\n`;
  const updated = upsertTotals(legacy);
  assert.match(updated, /keep me/);
  assert.match(updated, /<!-- \/screenmark-totals -->/);
});

test('upsertTotals is exactly idempotent', () => {
  const once = upsertTotals(BUDGET);
  assert.equal(upsertTotals(once), once);
});

const table = (rows: string, name = 'Production'): string => `## ${name}\n\n| Item | Estimate | Actual | Notes |\n|--|--|--|--|\n${rows}\n`;
const MARK = '<!-- generated by ScreenMark — edits here are overwritten -->';
const END = '<!-- /screenmark-totals -->';
const owned = `## Totals\n\n${MARK}\n\n| Section | Estimate | Actual | Variance |\n|--|--|--|--|\n| Production | $1 | $1 | — |\n| **Total** | **$1** | **$1** | **—** |`;

test('invalid nonempty amounts fail with source location', () => {
  for (const bad of ['0x10', '1e3', '$', '1,23', '1 2', '0.001', 'NaN', 'Infinity', '90071992547409.92']) {
    assert.throws(() => upsertTotals(table(`| a | ${bad} | | |`)), /line 5.*Production.*Estimate/i, bad);
  }
  assert.throws(() => parseBudget(table('| a | | nope | |')), /line 5.*Production.*Actual/i);
});

test('valid amounts retain decimal dollars and exact cent equality', () => {
  const budget = parseBudget(table('| a | 0.10 | 0.30 | |\n| b | 0.20 | | |\n| c | -$1,234.56 | $-1,234.56 | |'));
  assert.equal(budget.estimate, -1234.26);
  assert.equal(budget.actual, -1234.26);
  assert.match(renderTotals(budget), /\*\*—\*\*/);
  assert.doesNotMatch(renderTotals(budget), /\$0 under/);
  const publicBudget = { sections: [{ name: 'S', lines: [], estimate: 0.29, actual: 0.29 }], estimate: 0.29, actual: 0.29 };
  assert.match(renderTotals(publicBudget), /\$0\.29/);
  assert.throws(() => renderTotals({ ...publicBudget, estimate: 0.001 }), /cent/i);
  assert.throws(() => renderTotals({ ...publicBudget, actual: Infinity }), /safe|finite/i);
});

test('sum and variance overflow are rejected', () => {
  assert.throws(() => parseBudget(table('| a | 60000000000000 | 0 | |\n| b | 60000000000000 | 0 | |')), /line 6.*Production.*Estimate/i);
  assert.throws(() => parseBudget(table('| a | -60000000000000 | 60000000000000 | |')), /line 5.*Production.*Variance/i);
});

test('unowned Totals headings and source tables remain untouched and contribute', () => {
  const source = table('| Personal | 42 | 40 | do not delete |', 'Totals');
  const updated = upsertTotals(source);
  assert.ok(updated.startsWith(source));
  assert.equal(parseBudget(updated).estimate, 42);
  assert.equal(upsertTotals(updated), updated);
  assert.equal((updated.match(/## Totals/g) ?? []).length, 2);
});

test('multiple owned blocks refresh in place without losing intervening bytes', () => {
  const middle = '\n\nproducer notes  \n\n';
  const source = BUDGET + owned + '\n' + END + middle + owned + '\n' + END + '\ntrailing  \n';
  const updated = upsertTotals(source);
  assert.equal((updated.match(/\*\*\$1,800\*\*/g) ?? []).length, 2);
  assert.ok(updated.includes(middle));
  assert.ok(updated.endsWith('\ntrailing  \n'));
  assert.equal(upsertTotals(updated), updated);
});

test('distant sentinels and adjacent tables cannot expand generated ownership', () => {
  const tail = '\n| Item | Estimate | Actual | Notes |\n|--|--|--|--|\n| keep | 99 | 88 | original |\n\nproducer prose\n' + END + '\n';
  const updated = upsertTotals(BUDGET + owned + tail);
  assert.ok(updated.endsWith(tail));
  assert.equal(parseBudget(updated).estimate, 1800);
  assert.equal(upsertTotals(updated), updated);
});

test('legacy block without Total row stops before an adjacent table header', () => {
  const legacy = owned.slice(0, owned.indexOf('\n| **Total**'));
  const tail = '\n| Item | Estimate | Actual | Notes |\n|--|--|--|--|\n| keep | 99 | 88 | original |\n';
  const updated = upsertTotals(BUDGET + legacy + tail);
  assert.ok(updated.endsWith(tail));
  assert.equal(parseBudget(updated).estimate, 1800);
});

test('malformed owned regions fail before replacement', () => {
  assert.throws(() => upsertTotals(BUDGET + owned.replace('| Production | $1 | $1 | — |', '| Production | $1 |')), /line.*Totals/i);
  assert.throws(() => upsertTotals(BUDGET + '## Totals\n' + MARK + '\nproducer prose\n' + END), /line.*Totals/i);
});

test('escaped pipes and odd/even backslash runs retain correct columns', () => {
  const budget = parseBudget(table(String.raw`| Camera \| lens | 100 | 120 | kit |
| Slash \\| 20 | 30 | a \\\| b |`));
  assert.equal(budget.sections[0].lines[0].item, 'Camera | lens');
  assert.equal(budget.sections[0].lines[0].actual, 120);
  assert.equal(budget.sections[0].lines[1].item, 'Slash \\');
  assert.equal(budget.sections[0].lines[1].notes, 'a \\| b');
  assert.equal(budget.estimate, 120);
});

test('data row width is validated and table headers reset after prose', () => {
  assert.throws(() => parseBudget(table('| bad | 100 | 200 | extra | extra |')), /line 5.*Production.*width/i);
  const source = table('| first | 10 | 20 | |') + '\nprose\n| Item | Actual | Estimate |\n|--|--|--|\n| second | 30 | 40 |\n';
  const budget = parseBudget(source);
  assert.equal(budget.estimate, 50);
  assert.equal(budget.actual, 50);
});

test('CRLF refreshes and appends preserve all untouched bytes', () => {
  const source = (BUDGET + '\n\n').replace(/\n/g, '\r\n');
  const once = upsertTotals(source);
  assert.ok(once.startsWith(source));
  assert.doesNotMatch(once, /(?<!\r)\n/);
  const tail = '\r\n\r\nnotes  \r\n';
  assert.ok(upsertTotals(once + tail).endsWith(tail));
  assert.equal(upsertTotals(once), once);
});

test('section names are escaped in generated Markdown cells', () => {
  const output = upsertTotals(table('| a | 1 | 1 | |', String.raw`Camera | lens \ kit`));
  assert.ok(output.includes(String.raw`| Camera \| lens \\ kit |`));
  assert.equal(upsertTotals(output), output);
});


test('a section named like the final Total row cannot truncate generated ownership', () => {
  const source = table('| a | 10 | 9 | |', '**Total**') + table('| b | 20 | 19 | |', 'After');
  const once = upsertTotals(source);
  assert.equal(upsertTotals(once), once);
  assert.equal(parseBudget(once).estimate, 30);
});

test('large decimal amounts must survive both directions of the public cent round-trip', () => {
  assert.throws(() => upsertTotals(table('| a | 44072332189081.02 | | |')), /safe|round-trip/i);
});

test('empty marked tables are rejected as ambiguous generated blocks', () => {
  assert.throws(() => upsertTotals(BUDGET + owned.slice(0, owned.indexOf('\n| Production'))), /line.*Totals/i);
});
