import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseBudget, upsertTotals, budgetTemplate } from '../src/core/budget';

const BUDGET = `# Budget — Test

## Production

| Item | Estimate | Actual | Notes |
|------|----------|--------|-------|
| Crew | $1,000 | 1200.50 | ot |
| Camera | 500 | | rental |

## Post

| Item | Estimate | Actual | Notes |
|------|----------|--------|-------|
| Edit | 300 | 250 | |
`;

test('parseBudget sums sections and grand totals', () => {
  const b = parseBudget(BUDGET);
  assert.equal(b.sections.length, 2);
  assert.equal(b.sections[0].estimate, 1500);
  assert.equal(b.sections[0].actual, 1200.5);
  assert.equal(b.estimate, 1800);
  assert.equal(b.actual, 1450.5);
  assert.equal(b.sections[0].lines[1].actual, null);
});

test('upsertTotals appends then replaces in place', () => {
  const once = upsertTotals(BUDGET);
  assert.match(once, /## Totals/);
  assert.match(once, /\| Production \| \$1,500 \| \$1,200\.5 \|/);
  assert.match(once, /\*\*Total\*\* \| \*\*\$1,800\*\*/);
  // Running again must not duplicate the section or re-ingest it into totals.
  const twice = upsertTotals(once);
  assert.equal((twice.match(/## Totals/g) ?? []).length, 1);
  assert.match(twice, /\*\*Total\*\* \| \*\*\$1,800\*\*/);
});

test('totals section stays put when other sections follow it', () => {
  const withTail = upsertTotals(BUDGET) + '\n## Notes\n\nfree text\n';
  const updated = upsertTotals(withTail);
  assert.match(updated, /## Notes/);
  assert.equal((updated.match(/## Totals/g) ?? []).length, 1);
});

test('template parses cleanly with zero totals', () => {
  const b = parseBudget(budgetTemplate('X'));
  assert.equal(b.sections.length, 4);
  assert.equal(b.estimate, 0);
});

test('variance directions', () => {
  const over = upsertTotals('## S\n\n| Item | Estimate | Actual |\n|--|--|--|\n| a | 100 | 150 |\n');
  assert.match(over, /\+\$50 over/);
  const under = upsertTotals('## S\n\n| Item | Estimate | Actual |\n|--|--|--|\n| a | 100 | 80 |\n');
  assert.match(under, /\$20 under/);
});

test('user notes below the Totals table survive regeneration', () => {
  const withNotes = upsertTotals(BUDGET) + '\nrenegotiate crew rate\ninsurance quote pending\n';
  const updated = upsertTotals(withNotes);
  assert.match(updated, /renegotiate crew rate/);
  assert.match(updated, /insurance quote pending/);
  assert.equal((updated.match(/## Totals/g) ?? []).length, 1);
});

test('h3 subsection between Totals and next h2 survives', () => {
  const doc = upsertTotals(BUDGET).replace(/$/, '\n### Notes from producer\n\nKeep this paragraph.\n\n## Appendix\n\nmisc\n');
  const updated = upsertTotals(doc);
  assert.match(updated, /### Notes from producer/);
  assert.match(updated, /Keep this paragraph\./);
  assert.match(updated, /## Appendix/);
});

test('legacy Totals block without end sentinel is bounded by the table, not the next h2', () => {
  const legacy = `${BUDGET}\n## Totals\n\n<!-- generated by ScreenMark — edits here are overwritten -->\n\n| Section | Estimate | Actual | Variance |\n|--|--|--|--|\n| Production | $1 | $1 | — |\n\nkeep me\n`;
  const updated = upsertTotals(legacy);
  assert.match(updated, /keep me/);
  assert.match(updated, /<!-- \/screenmark-totals -->/);
});

test('upsertTotals is exactly idempotent', () => {
  const once = upsertTotals(BUDGET);
  assert.equal(upsertTotals(once), once);
});

test('parseMoney rejects hex and exponent forms', () => {
  const b = parseBudget('## S\n\n| Item | Estimate | Actual |\n|--|--|--|\n| a | 0x10 | 1e3 |\n| b | -50 | $1,234.56 |\n');
  assert.equal(b.sections[0].lines[0].estimate, null);
  assert.equal(b.sections[0].lines[0].actual, null);
  assert.equal(b.sections[0].lines[1].estimate, -50);
  assert.equal(b.sections[0].lines[1].actual, 1234.56);
});
