import { escapeMarkdownCell } from './markdown';

export interface BudgetLine {
  item: string;
  estimate: number | null;
  actual: number | null;
  notes: string;
}

export interface BudgetSection {
  name: string;
  lines: BudgetLine[];
  estimate: number;
  actual: number;
}

export interface Budget {
  sections: BudgetSection[];
  estimate: number;
  actual: number;
}

const TOTALS_HEADING = '## Totals';
const GENERATED_MARK = '<!-- generated by ScreenMark — edits here are overwritten -->';
const GENERATED_END = '<!-- /screenmark-totals -->';

type Location = { line: number; section: string; column: string };
function fail(at: Location, detail: string): never {
  throw new Error(`Budget line ${at.line}, section "${at.section}", column ${at.column}: ${detail}`);
}

// Cents must also survive the public numeric-dollar interface without losing precision.
function checkedCents(cents: number, at: Location): number {
  if (!Number.isSafeInteger(cents)) fail(at, 'amount or arithmetic exceeds safe integer cents.');
  const dollars = cents / 100;
  if (Math.round(dollars * 100) !== cents || BigInt(dollars.toFixed(2).replace('.', '')) !== BigInt(cents)) {
    fail(at, 'amount cannot round-trip safely through numeric dollars.');
  }
  return cents;
}

function publicCents(dollars: number, at: Location): number {
  if (!Number.isFinite(dollars)) fail(at, 'amount must be finite and safe.');
  const cents = checkedCents(Math.round(dollars * 100), at);
  if (cents / 100 !== dollars) fail(at, 'amount must contain whole cents.');
  return cents;
}

function parseMoney(cell: string, at: Location): number | null {
  if (cell === '') return null;
  // Permit either -$1 or $-1, but not internal whitespace or loose comma grouping.
  const match = /^(?:(-)\$?|\$(-)?|)(\d+|\d{1,3}(?:,\d{3})+)(?:\.(\d{1,2}))?$/.exec(cell);
  if (!match) fail(at, `invalid amount "${cell}"; use decimal dollars with at most two decimal places.`);
  const magnitude = BigInt(match[3].replace(/,/g, '')) * 100n + BigInt((match[4] ?? '').padEnd(2, '0'));
  const cents = (match[1] || match[2]) ? -magnitude : magnitude;
  if (cents > BigInt(Number.MAX_SAFE_INTEGER) || cents < BigInt(Number.MIN_SAFE_INTEGER)) {
    fail(at, 'amount exceeds safe integer cents.');
  }
  return checkedCents(Number(cents), at);
}

/** Decode escaped pipes/backslashes while identifying only unescaped cell boundaries. */
function splitRow(line: string): string[] | null {
  const text = line.trim();
  if (!text.startsWith('|')) return null;
  const cells: string[] = [];
  let cell = '';
  for (let i = 1; i < text.length; i++) {
    const ch = text[i];
    if (ch === '\\' && (text[i + 1] === '\\' || text[i + 1] === '|')) {
      cell += text[++i];
    } else if (ch === '|') {
      cells.push(cell.trim());
      cell = '';
      if (i === text.length - 1) return cells;
    } else {
      cell += ch;
    }
  }
  return null;
}

const isDividerRow = (cells: string[] | null): boolean => !!cells?.length && cells.every((c) => /^:?-+:?$/.test(c));
type SourceLine = { text: string; start: number; end: number };
type GeneratedRegion = { first: number; last: number };

function sourceLines(md: string): SourceLine[] {
  const lines: SourceLine[] = [];
  for (const match of md.matchAll(/[^\r\n]*(?:\r\n|\n|$)/g)) {
    if (!match[0]) continue;
    const text = match[0].replace(/\r?\n$/, '');
    lines.push({ text, start: match.index!, end: match.index! + text.length });
  }
  return lines;
}

/** A marker grants ownership only to the immediately following recognizable table. */
function generatedRegions(lines: SourceLine[]): GeneratedRegion[] {
  const regions: GeneratedRegion[] = [];
  for (let first = 0; first < lines.length; first++) {
    if (!/^##\s+Totals\s*$/i.test(lines[first].text)) continue;
    let i = first + 1;
    while (i < lines.length && lines[i].text.trim() === '') i++;
    if (lines[i]?.text.trim() !== GENERATED_MARK) continue;
    const at = (line: number): Location => ({ line: line + 1, section: 'Totals', column: 'generated table' });
    i++;
    while (i < lines.length && lines[i].text.trim() === '') i++;
    const header = splitRow(lines[i]?.text ?? '');
    if (header?.map((c) => c.toLowerCase()).join('|') !== 'section|estimate|actual|variance') {
      fail(at(i), 'generated marker must be followed by the Section / Estimate / Actual / Variance table.');
    }
    const divider = splitRow(lines[i + 1]?.text ?? '');
    if (divider?.length !== 4 || !isDividerRow(divider)) fail(at(i + 1), 'malformed generated table divider.');
    i += 2;
    const firstRow = i;
    let last = i - 1;
    for (; i < lines.length; i++) {
      const cells = splitRow(lines[i].text);
      if (!cells) {
        if (lines[i].text.trim().startsWith('|')) fail(at(i), 'malformed generated table row.');
        break;
      }
      // An adjacent table has its own header and divider, even in legacy blocks.
      if (isDividerRow(splitRow(lines[i + 1]?.text ?? ''))) break;
      if (cells.length !== 4 || isDividerRow(cells)) fail(at(i), 'malformed generated table row width.');
      last = i;
      if (cells[0] === '**Total**' && cells.slice(1).every((cell) => /^\*\*.+\*\*$/.test(cell))) break;
    }
    if (last < firstRow) fail(at(i), 'generated table has no data rows.');
    // No search beyond the table boundary: later notes and sentinels belong to the author.
    if (lines[last + 1]?.text.trim() === GENERATED_END) last++;
    regions.push({ first, last });
    first = last;
  }
  return regions;
}

function parseLines(lines: SourceLine[], regions: GeneratedRegion[]): Budget {
  const sections: BudgetSection[] = [];
  let section: BudgetSection | null = null;
  let cols: { item: number; estimate: number; actual: number; notes: number; width: number } | null = null;
  let sectionEstimate = 0;
  let sectionActual = 0;
  let estimate = 0;
  let actual = 0;
  const starts = new Map(regions.map((region) => [region.first, region.last]));

  for (let i = 0; i < lines.length; i++) {
    const last = starts.get(i);
    if (last !== undefined) {
      i = last;
      section = null;
      cols = null;
      continue;
    }
    const line = lines[i].text;
    const heading = line.match(/^##\s+(.*)$/);
    if (heading) {
      section = { name: heading[1].trim(), lines: [], estimate: 0, actual: 0 };
      sections.push(section);
      sectionEstimate = sectionActual = 0;
      cols = null;
      continue;
    }
    const cells = splitRow(line);
    if (!cells) {
      if (cols && section && line.trim().startsWith('|')) {
        fail({ line: i + 1, section: section.name, column: 'row width' }, 'malformed table row.');
      }
      cols = null;
      continue;
    }
    if (!section) continue;
    const at = (column: string): Location => ({ line: i + 1, section: section!.name, column });
    if (isDividerRow(cells)) {
      if (cols && cells.length !== cols.width) fail(at('row width'), `expected ${cols.width} cells, found ${cells.length}.`);
      continue;
    }
    if (!cols) {
      const lowered = cells.map((c) => c.toLowerCase());
      if (lowered.includes('estimate')) {
        cols = {
          item: Math.max(0, lowered.findIndex((c) => c === 'item' || c === 'line item')),
          estimate: lowered.indexOf('estimate'), actual: lowered.indexOf('actual'),
          notes: lowered.indexOf('notes'), width: cells.length,
        };
      }
      continue;
    }
    if (cells.length !== cols.width) fail(at('row width'), `expected ${cols.width} cells, found ${cells.length}.`);
    const rowEstimate = parseMoney(cells[cols.estimate], at('Estimate'));
    const rowActual = cols.actual < 0 ? null : parseMoney(cells[cols.actual], at('Actual'));
    sectionEstimate = checkedCents(sectionEstimate + (rowEstimate ?? 0), at('Estimate'));
    sectionActual = checkedCents(sectionActual + (rowActual ?? 0), at('Actual'));
    estimate = checkedCents(estimate + (rowEstimate ?? 0), at('Estimate'));
    actual = checkedCents(actual + (rowActual ?? 0), at('Actual'));
    checkedCents(sectionActual - sectionEstimate, at('Variance'));
    checkedCents(actual - estimate, at('Variance'));
    section.lines.push({
      item: cells[cols.item], estimate: rowEstimate === null ? null : rowEstimate / 100,
      actual: rowActual === null ? null : rowActual / 100, notes: cols.notes < 0 ? '' : cells[cols.notes],
    });
    section.estimate = sectionEstimate / 100;
    section.actual = sectionActual / 100;
  }
  return { sections: sections.filter((s) => s.lines.length > 0), estimate: estimate / 100, actual: actual / 100 };
}

/** Parse source budget tables, excluding only positively identified generated regions. */
export function parseBudget(md: string): Budget {
  const lines = sourceLines(md);
  return parseLines(lines, generatedRegions(lines));
}

const money = (cents: number): string => {
  const absolute = BigInt(Math.abs(cents));
  const fraction = (absolute % 100n).toString().padStart(2, '0').replace(/0+$/, '');
  return `$${cents < 0 ? '-' : ''}${(absolute / 100n).toLocaleString('en-US')}${fraction ? '.' + fraction : ''}`;
};

function varianceCell(estimate: number, actual: number, at: Location): string {
  const v = checkedCents(actual - estimate, at);
  if (v === 0) return '—';
  return v > 0 ? `+${money(v)} over` : `${money(-v)} under`;
}

export function renderTotals(budget: Budget): string {
  const out: string[] = [TOTALS_HEADING, '', GENERATED_MARK, '',
    '| Section | Estimate | Actual | Variance |', '|---------|----------|--------|----------|'];
  const row = (name: string, estimate: number, actual: number, total = false): string => {
    const at = (column: string): Location => ({ line: 1, section: name, column });
    const e = publicCents(estimate, at('Estimate'));
    const a = publicCents(actual, at('Actual'));
    const cells = [escapeMarkdownCell(name), money(e), money(a), varianceCell(e, a, at('Variance'))];
    return `| ${cells.map((cell) => total ? `**${cell}**` : cell).join(' | ')} |`;
  };
  for (const s of budget.sections) out.push(row(s.name, s.estimate, s.actual));
  out.push(row('Total', budget.estimate, budget.actual, true), GENERATED_END);
  return out.join('\n');
}

/** Replace all owned blocks by byte offsets; every byte outside those ranges survives. */
export function upsertTotals(md: string): string {
  const lines = sourceLines(md);
  const regions = generatedRegions(lines);
  const newline = md.match(/\r?\n/)?.[0] ?? '\n';
  const totals = renderTotals(parseLines(lines, regions)).replace(/\n/g, newline);
  if (!regions.length) {
    const separator = !md || md.endsWith(newline + newline) ? '' : md.endsWith(newline) ? newline : newline + newline;
    return md + separator + totals + newline;
  }
  let result = '';
  let previous = 0;
  for (const region of regions) {
    result += md.slice(previous, lines[region.first].start) + totals;
    previous = lines[region.last].end;
  }
  return result + md.slice(previous);
}

export function budgetTemplate(title: string): string {
  const section = (name: string, rows: string[][]): string =>
    [
      `## ${name}`,
      '',
      '| Item | Estimate | Actual | Notes |',
      '|------|----------|--------|-------|',
      ...rows.map((r) => `| ${r.join(' | ')} |`),
      '',
    ].join('\n');

  return [
    `# Budget — ${title}`,
    '',
    'Fill in Estimate/Actual (plain numbers or $1,234.56). Run **ScreenMark: Budget Summary** to refresh the Totals section.',
    '',
    section('Above the Line', [
      ['Writer', '', '', ''],
      ['Director', '', '', ''],
      ['Producers', '', '', ''],
      ['Cast', '', '', ''],
    ]),
    section('Production', [
      ['Crew', '', '', ''],
      ['Locations', '', '', ''],
      ['Equipment (camera/grip/electric)', '', '', ''],
      ['Art / props / wardrobe', '', '', ''],
      ['Catering & transport', '', '', ''],
    ]),
    section('Post-Production', [
      ['Editing', '', '', ''],
      ['Sound & music', '', '', ''],
      ['Color', '', '', ''],
      ['VFX', '', '', ''],
    ]),
    section('Other', [
      ['Insurance', '', '', ''],
      ['Contingency (10%)', '', '', ''],
    ]),
  ].join('\n');
}
