export interface BudgetLine {
  item: string;
  estimate: number | null;
  actual: number | null;
  notes: string;
}

export interface BudgetSection {
  name: string;
  lines: BudgetLine[];
  estimate: number;
  actual: number;
}

export interface Budget {
  sections: BudgetSection[];
  estimate: number;
  actual: number;
}

const TOTALS_HEADING = '## Totals';
const GENERATED_MARK = '<!-- generated by ScreenMark — edits here are overwritten -->';
const GENERATED_END = '<!-- /screenmark-totals -->';

function parseMoney(cell: string): number | null {
  const cleaned = cell.replace(/[$,\s]/g, '');
  if (cleaned === '') return null;
  // Strict decimal only — Number() would accept 0x10 / 1e3 and turn typos into money.
  if (!/^-?\d+(\.\d+)?$/.test(cleaned)) return null;
  return Number(cleaned);
}

function splitRow(line: string): string[] {
  return line
    .replace(/^\s*\|/, '')
    .replace(/\|\s*$/, '')
    .split('|')
    .map((c) => c.trim());
}

const isTableRow = (line: string): boolean => /^\s*\|.*\|\s*$/.test(line);
const isDividerRow = (cells: string[]): boolean => cells.every((c) => /^:?-+:?$/.test(c));

/** Parse a budget markdown doc: `## Section` headings each followed by a table with Estimate/Actual columns. */
export function parseBudget(md: string): Budget {
  const lines = md.split(/\r?\n/);
  const sections: BudgetSection[] = [];
  let section: BudgetSection | null = null;
  let cols: Record<string, number> | null = null;

  for (const line of lines) {
    const heading = line.match(/^##\s+(.*)$/);
    if (heading) {
      const name = heading[1].trim();
      cols = null;
      if (name.toLowerCase() === 'totals') {
        section = null; // never re-ingest our own generated section
      } else {
        section = { name, lines: [], estimate: 0, actual: 0 };
        sections.push(section);
      }
      continue;
    }
    if (!section || !isTableRow(line)) continue;
    const cells = splitRow(line);
    if (isDividerRow(cells)) continue;
    if (!cols) {
      // Header row: locate columns by name.
      const lowered = cells.map((c) => c.toLowerCase());
      if (lowered.includes('estimate')) {
        cols = {
          item: Math.max(0, lowered.findIndex((c) => c === 'item' || c === 'line item')),
          estimate: lowered.indexOf('estimate'),
          actual: lowered.indexOf('actual'),
          notes: lowered.indexOf('notes'),
        };
      }
      continue;
    }
    const entry: BudgetLine = {
      item: cells[cols.item] ?? '',
      estimate: cols.estimate >= 0 ? parseMoney(cells[cols.estimate] ?? '') : null,
      actual: cols.actual >= 0 ? parseMoney(cells[cols.actual] ?? '') : null,
      notes: cols.notes >= 0 ? (cells[cols.notes] ?? '') : '',
    };
    section.lines.push(entry);
    section.estimate += entry.estimate ?? 0;
    section.actual += entry.actual ?? 0;
  }

  const withTables = sections.filter((s) => s.lines.length > 0);
  return {
    sections: withTables,
    estimate: withTables.reduce((sum, s) => sum + s.estimate, 0),
    actual: withTables.reduce((sum, s) => sum + s.actual, 0),
  };
}

const money = (n: number): string => `$${n.toLocaleString('en-US', { maximumFractionDigits: 2 })}`;

function varianceCell(estimate: number, actual: number): string {
  const v = actual - estimate;
  if (v === 0) return '—';
  return v > 0 ? `+${money(v)} over` : `${money(-v)} under`;
}

export function renderTotals(budget: Budget): string {
  const out: string[] = [
    TOTALS_HEADING,
    '',
    GENERATED_MARK,
    '',
    '| Section | Estimate | Actual | Variance |',
    '|---------|----------|--------|----------|',
  ];
  for (const s of budget.sections) {
    out.push(`| ${s.name} | ${money(s.estimate)} | ${money(s.actual)} | ${varianceCell(s.estimate, s.actual)} |`);
  }
  out.push(
    `| **Total** | **${money(budget.estimate)}** | **${money(budget.actual)}** | **${varianceCell(budget.estimate, budget.actual)}** |`,
    GENERATED_END
  );
  return out.join('\n');
}

/**
 * Replace (or append) the generated `## Totals` block, leaving everything else
 * untouched. The block is bounded by GENERATED_END; for blocks written before
 * that sentinel existed, fall back to scanning only over the generated shape
 * (blank lines, the marker, table rows) so user prose below is never eaten.
 */
export function upsertTotals(md: string): string {
  const totals = renderTotals(parseBudget(md));
  const start = md.search(new RegExp(`^${TOTALS_HEADING}\\s*$`, 'm'));
  if (start === -1) {
    return md.replace(/\s*$/, '\n\n') + totals + '\n';
  }

  let end = md.indexOf(GENERATED_END, start);
  if (end !== -1) {
    end += GENERATED_END.length;
  } else {
    end = start + TOTALS_HEADING.length;
    for (const lineMatch of md.slice(end).matchAll(/[^\n]*\n?/g)) {
      const line = lineMatch[0];
      const t = line.trim();
      const generatedShape = t === '' || t === GENERATED_MARK || /^\|.*\|$/.test(t);
      if (!generatedShape) break;
      end += line.length;
      if (line.indexOf('\n') === -1) break; // last line of file
    }
    end = start + md.slice(start, end).replace(/\s+$/, '').length; // don't swallow trailing blank gap
  }

  const suffix = md.slice(end).replace(/^\s*\n/, '');
  return md.slice(0, start) + totals + (suffix.trim() ? '\n\n' + suffix : '\n');
}

export function budgetTemplate(title: string): string {
  const section = (name: string, rows: string[][]): string =>
    [
      `## ${name}`,
      '',
      '| Item | Estimate | Actual | Notes |',
      '|------|----------|--------|-------|',
      ...rows.map((r) => `| ${r.join(' | ')} |`),
      '',
    ].join('\n');

  return [
    `# Budget — ${title}`,
    '',
    'Fill in Estimate/Actual (plain numbers or $1,234.56). Run **ScreenMark: Budget Summary** to refresh the Totals section.',
    '',
    section('Above the Line', [
      ['Writer', '', '', ''],
      ['Director', '', '', ''],
      ['Producers', '', '', ''],
      ['Cast', '', '', ''],
    ]),
    section('Production', [
      ['Crew', '', '', ''],
      ['Locations', '', '', ''],
      ['Equipment (camera/grip/electric)', '', '', ''],
      ['Art / props / wardrobe', '', '', ''],
      ['Catering & transport', '', '', ''],
    ]),
    section('Post-Production', [
      ['Editing', '', '', ''],
      ['Sound & music', '', '', ''],
      ['Color', '', '', ''],
      ['VFX', '', '', ''],
    ]),
    section('Other', [
      ['Insurance', '', '', ''],
      ['Contingency (10%)', '', '', ''],
    ]),
  ].join('\n');
}
